### ISSUE TITLE
MDM enrolled condition outputs no data in the keys

### ISSUE THREAD

**Issue by poundbangbash** [carlashley/munkicon#5]
Attempted fix at https://github.com/carlashley/munkicon/pull/4

Prior to the PR the output in the plist was:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>enrolled_via_dep</key>
	<string></string>
	<key>mdm_enrollment</key>
	<string></string>
</dict>
</plist>
```

**Comment by carlashley** [comment]
I'm currently re-writing all the conditionals so I'll hold off on this PR for the moment, but thanks for submitting it :)

**Comment by carlashley** [comment]
This should be resolved now @poundbangbash - tested on my system and it's generating the right output now.

**Comment by poundbangbash** [comment]
Verified working here as well.
